### ISSUE TITLE
This is not an issue but a doubt

### ISSUE THREAD

**Issue by tibinthomas** [hapinessjs/ng-universal-module#24]
If I need to add a new middle were in server.js file. How can I do it?

In case of pure express app I can do it as follows:

eg:

import * as cookieParser from 'cookie-parser';
 
app.use(cookieParser('Your private token'));

**Comment by tibinthomas** [comment]
Is this is correct

  onStart(): void {
    this._httpServer.instance().app.use(cookieParser); // concerned line of code
    console.log(`Node server listening on ${this._httpServer.instance().info.uri}`);
  }

**Comment by njl07** [comment]
@tibinthomas you can not use it like this. You have to use `HttpInterceptor` from `Angular` to get your cookie in the front application.

The `SSR` is just to render the content and the the cookie should come from an another API/server because you can't do something inside the server of `SSR`

[Here](https://github.com/hapinessjs/ng-universal-example/blob/master/src/app/shared/interceptors/my-http.interceptor.ts) an example of the creation of a `HttpInterceptor` with the injection of `REQUEST` object from the server
